<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FKH366F" failures="1" tests="4" name="com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality" time="10.821" errors="0" timestamp="25 Apr 2018 17:36:48 GMT" skipped="1">
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality" name="Test_LoginToOrion_IsSuccess" time="1.040"/>
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality" name="Test_IfNewTimeSheetPage_Isdisplayed" time="2.361"/>
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality" name="Test_IfDatanotSaved" time="7.420">
    <failure message="New Time Period 04/22/2018 - 04/28/2018 Exist.  FAILED expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: New Time Period 04/22/2018 - 04/28/2018 Exist.  FAILED expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality.Test_IfDatanotSaved(Test_NewTimeSheet_CancelFunctionality.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_IfDatanotSaved -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality" name="Test_LogoutfromOrion_IsSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- Test_LogoutfromOrion_IsSuccess -->
</testsuite> <!-- com.orion.qa.testcases.Test_NewTimeSheet_CancelFunctionality -->
