<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FKH366F" failures="1" tests="7" name="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" time="4.137" errors="0" timestamp="09 May 2018 17:12:40 GMT" skipped="3">
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_LoginToOrion_IsSuccess" time="2.257"/>
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_IfEditTimeSheetPage_Isdisplayed" time="1.789"/>
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_VerifyUserCanEnterTime" time="0.038"/>
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_VerifyUserAddAttachment" time="0.053">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertFalse(Assert.java:62)
	at org.testng.Assert.assertFalse(Assert.java:72)
	at com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality.Test_VerifyUserAddAttachment(Test_SubmittedTimeSheet_SaveFunctionality.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_VerifyUserAddAttachment -->
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_VerifyUserAddcomment" time="0.000">
    <skipped/>
  </testcase> <!-- Test_VerifyUserAddcomment -->
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_SaveButton_IsDisplayed" time="0.000">
    <skipped/>
  </testcase> <!-- Test_SaveButton_IsDisplayed -->
  <testcase classname="com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality" name="Test_LogoutfromOrion_IsSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- Test_LogoutfromOrion_IsSuccess -->
</testsuite> <!-- com.orion.qa.testcases.Test_SubmittedTimeSheet_SaveFunctionality -->
